version: "3"

services:
  #dbコンテナ
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
  #webコンテナ
  web:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./src:/docker-rails-test
volumes:
  db-data:
