services:
  db:
    build:
      context: ./infra/prod/db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: ./infra/prod/app/Dockerfile
    depends_on:
      - db
    environment:
      RAILS_ENV: production

  web:
    build:
      context: ./infra/prod/web
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./infra/prod/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/public:/docker-rails-test/public

volumes:
  db-data:
