name: CI TEST
run-name: ${{ github.actor }} is CI testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build with Docker Compose
        run: docker compose -f compose.yml build
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}

      - name: Run containers
        run: docker compose -f compose.yml up -d

      - name: Run unit test
        run: docker compose -f compose.yml exec -T app bin/rails test

      - name: Shutdown
        run: docker compose down
