name: CI TEST
run-name: ${{ github.actor }} is CI testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build with Docker Compose
        run: docker compose -f compose.yml build

      - name: Run containers
        run: docker compose -f compose.yml up -d

      - name: Shutdown
        run: docker compose down
