name: CI TEST
run-name: ${{ github.actor }} is CI testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build with Docker Compose using Buildx
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          cache-from: type=gha,scope=$GITHUB_REF_NAME
          cache-to: type=gha,scope=$GITHUB_REF_NAME,mode=max

      - name: Run containers
        run: docker compose -f compose.yml up -d

      - name: Run compose ps
        run: docker compose -f compose.yml ps

      - name: Shutdown
        run: docker compose down
